### ISSUE TITLE
Multiple protocols

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#534]
There's some reasons it might be good to have multiple protocols:

- Clamping both membrane potential and a concentration to some time signal (e.g. Vm and Ca)

This would require quite major changes in Myokit.

~One way to implement this might be to remove the "binding" construct, and replace it with some special function (`myokit.Expression`), e.g.~

```
I_stim = input('pace') * stim_amplitude
I_diff = input('diffusion_current')
```
~where 'diffusion_current' would be a name set by the simulation (but customisable?), while the name 'pace' would be set by the user, e.g. by having a `name: pace` field in the protocol definition, or a constructor like `p = myokit.Protocol('pace')`.~

A different way to implement it would be to set it in the simulation, e.g.

```
s.set_protocol('pace', p)
s.set_protocol('other_label', q)
```

**Comment by MichaelClerx** [comment]
A "least resistance" way in could be to start with #386, then go
```
def set_protocol(protocol, label='pace')
```
but don't allow more than one protocol initially. Then it's up to simulations to decide if they want to support multiple, but there's a clear way to do it without syntax changes

**Comment by MichaelClerx** [comment]
A major difficulty with this is that it is no longer known at compile time whether a variable is "bound" or not. (Even if we would have e.g. `bind pace1`, `bind pace2` etc., the usual step is to _remove all unused bindings before compilation_).

Roadmap:

- [ ] Get rid of the "binding" concept, replace it with labels
  - [ ] Remove `prepare_bindings` (and need for it) in simulations https://github.com/MichaelClerx/myokit/issues/601
  - [ ] Scan for is_bound checks listed here and figure out how to avoid them https://github.com/MichaelClerx/myokit/issues/386. Might also involve this one: https://github.com/MichaelClerx/myokit/issues/832
  - [ ] Update API docs https://github.com/MichaelClerx/myokit/issues/386
  - [ ] Update external examples https://github.com/MichaelClerx/myokit/issues/833
- [ ] Allow label to be specified, make sure sims expect this to be something that can change repeatedly post-compilation https://github.com/MichaelClerx/myokit/issues/732
- [ ] This issue https://github.com/MichaelClerx/myokit/issues/320 will probably disappear once we've done this?

**Comment by martinjrobins** [comment]
Hi @MichaelClerx, I'd be happy to work on this if this would be helpful? Anywhere in particular I should start? should I follow the roadmap above, starting at #601 ?

**Comment by martinjrobins** [comment]
actually, I don't think you can do a dynamic set of protocols unless you want to slow it down a bit, since you use #defines to refer to variables in expressions, so I think everything has to be known at compile time?

**Comment by martinjrobins** [comment]
so what I ended up doing was: at compile time the cmodel and cvodesim.c is compiled knowing a list of pacing labels/variables. The user is free to then set/clear the protocol assocated with each variable as much as they like, and these protocols are passed in whenever the simulation is run. But the list of pacing variables can never change as this is set in the compiled c-code.

**Comment by martinjrobins** [comment]
@MichaelClerx: any insight into the fixed form pacing above. I've created a python class called `FixedProtocol` as an equivilent to `Protocol`, but this currently behaves differently from the c-code as I enforce `bisect_left` behaviour, so that the (passing) test is:

```python
def test_values(self):
        values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        times =  [0, 0, 1, 1, 1, 2, 2, 2, 3, 4, 5, 7]
        values = list(range(len(times)))
        pacing = myokit.FixedProtocol(times, values)

        def test(value, index):
            self.assertEqual(pacing.pace(value), index)

        test(-1, 0)
        test(0, 0)
        test(1, 2)
        test(2, 5)
        test(3, 8)
        test(4, 9)
        test(5, 10)
        test(7, 11)
        test(8, 11)
        test(1.5, 4.5)
        test(1.75, 4.75)
        test(6, 10.5)
        test(5.5, 10.25)

```

**Comment by MichaelClerx** [comment]
> 



> @MichaelClerx: any insight into the fixed form pacing above. I've created a python class called `FixedProtocol` as an equivilent to `Protocol`, but this currently behaves differently from the c-code as I enforce `bisect_left` behaviour, so that the (passing) test is:
> 
> ```python
> def test_values(self):
>         values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
>         times =  [0, 0, 1, 1, 1, 2, 2, 2, 3, 4, 5, 7]
>         values = list(range(len(times)))
>         pacing = myokit.FixedProtocol(times, values)
> 
>         def test(value, index):
>             self.assertEqual(pacing.pace(value), index)
> 
>         test(-1, 0)
>         test(0, 0)
>         test(1, 2)
>         test(2, 5)
>         test(3, 8)
>         test(4, 9)
>         test(5, 10)
>         test(7, 11)
>         test(8, 11)
>         test(1.5, 4.5)
>         test(1.75, 4.75)
>         test(6, 10.5)
>         test(5.5, 10.25)
> ```

I think the right-most would make most sense? Not set in stone, as an edge case of rarely used functionality :D

**Comment by MichaelClerx** [comment]
> so what I ended up doing was: at compile time the cmodel and cvodesim.c is compiled knowing a list of pacing labels/variables. The user is free to then set/clear the protocol assocated with each variable as much as they like, and these protocols are passed in whenever the simulation is run. But the list of pacing variables can never change as this is set in the compiled c-code.

Cool. I just looked at my original comments in the issue and I think I was planning to do something like have a dict that maps strings to memory addresses, so that the C code could take a string and know which var to overwrite. Would get very tricky if dependencies are allowed though. E.g.

```
x = 1 + z
y = 5 + x
overrule x = protocol #1
```
would have to somehow know to become

```
x = 1 + z
overrule x = protocol #1
y = 5 + x
```
etc.

So your method is probably better. Although it means #320 is still an issue (with protocols set fully dynamically, this would have disappeared).

**Comment by MichaelClerx** [comment]
@martinjrobins I think the left-right bisection mix was to allow instantaneous jumps at points in time!

https://nbviewer.org/github/myokit/myokit-examples/blob/main/technical-notes/1-1-pacing.ipynb

So you'd interpolate with x-left on the left hand side, with x-right on the right hand side

**Comment by martinjrobins** [comment]
but the issue is what to do in the middle :) If the jump is at t=1, what do you do at t=1, left or right?

**Comment by martinjrobins** [comment]
yea, that makes sense, lets lock in `bisect_right` then!
